# Generated by Django 4.2 on 2024-05-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='det',
            field=models.TextField(blank=True, null=True),
        ),
    ]
