# Generated by Django 4.2 on 2024-05-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_product_det'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='det',
            new_name='detail',
        ),
    ]
